import random
import requests

words = ['Abuse',
         'Adult',
         'Agent',
         'Anger',
         'Apple',
         'Award',
         'Basis',
         'Beach',
         'Birth',
         'Block',
         'Blood',
         'Cause',
         'Chain',
         'Chair',
         'Chest',
         'Chief',
         'Child',
         'China',
         'Claim',
         'Class',
         'Clock',
         'Coach',
         'Coast',
         'Court',
         'Cover',
         'Cream',
         'Crime',
         'Cross',
         'Crowd',
         'Crown',
         'Cycle',
         'Dance',
         'Death',
         'Depth',
         'Doubt',
         'Draft',
         'Drama',
         'Dream',
         'Dress',
         'Drink',
         'Drive',
         'Earth',
         'Enemy',
         'Entry',
         'Error',
         'Event',
         'Faith',
         'Fault',
         'Field',
         'Fight',
         'Final',
         'Floor',
         'Focus',
         'Force',
         'Frame',
         'Frank',
         'Front',
         'Fruit',
         'Glass',
         'Grant',
         'Grass',
         'Green',
         'Group',
         'Guide',
         'Heart',
         'Henry',
         'Horse',
         'Hotel',
         'House',
         'Image',
         'Index',
         'Input',
         'Issue',
         'Judge',
         'Knife',
         'Laura',
         'Layer',
         'Level',
         'Lewis',
         'Light',
         'Limit',
         'Lunch',
         'Major',
         'March',
         'Match',
         'Metal',
         'Model',
         'Money',
         'Month',
         'Motor',
         'Mouth',
         'Music',
         'Night',
         'Noise',
         'North',
         'Novel',
         'Nurse',
         'Offer',
         'Order',
         'Other',
         'Owner',
         'Panel',
         'Paper',
         'Party',
         'Peace',
         'Peter',
         'Phase',
         'Phone',
         'Piece',
         'Pilot',
         'Pitch',
         'Place',
         'Plane',
         'Plant',
         'Plate',
         'Point',
         'Pound',
         'Power',
         'Press',
         'Price',
         'Pride',
         'Prize',
         'Proof',
         'Queen',
         'Radio',
         'Range',
         'Ratio',
         'Reply',
         'Right',
         'River',
         'Round',
         'Route',
         'Rugby',
         'Scale',
         'Scene',
         'Scope',
         'Score',
         'Sense',
         'Shape',
         'Share',
         'Sheep',
         'Sheet',
         'Shift',
         'Shirt',
         'Shock',
         'Sight',
         'Simon',
         'Skill',
         'Sleep',
         'Smile',
         'Smith',
         'Smoke',
         'Sound',
         'South',
         'Space',
         'Speed',
         'Spite',
         'Sport',
         'Squad',
         'Staff',
         'Stage',
         'Start',
         'State',
         'Steam',
         'Steel',
         'Stock',
         'Stone',
         'Store',
         'Study',
         'Stuff',
         'Style',
         'Sugar',
         'Table',
         'Taste',
         'Terry',
         'Theme',
         'Thing',
         'Title',
         'Total',
         'Touch',
         'Tower',
         'Track',
         'Trade',
         'Train',
         'Trend',
         'Trial',
         'Trust',
         'Truth',
         'Uncle',
         'Union',
         'Unity',
         'Value',
         'Video',
         'Visit',
         'Voice',
         'Waste',
         'Watch',
         'Water',
         'While',
         ' White',
         'Whole',
         'Woman',
         'World',
         'Youth']
words = [i.lower() for i in words]
index_value = random.randint(0, 10)
word = words[index_value]
count = 0
guess = "nuuuu"
while count < 6 or guess != word:
    count += 1
    correct = []
    guess = input("What is your guess? \n")
    response = requests.get(
        "https://api.dictionaryapi.dev/api/v2/entries/en/"+guess)
    if response.status_code == 200:
        pass
    else:
        print("The word does not exist")
        count -= 1
        continue
    if len(guess) != 5:
        print("Invalid Character length")
        break
    output = ["_", "_", "_", "_", "_"]
    main_chars = []
    for i in range(5):
        if word[i] == guess[i]:
            output.pop(i)
            output.insert(i, word[i])
            main_chars.append(word[i])
    print("".join(output))

    other_chars = []
    for i in range(5):
        if guess[i] in word:
            if guess[i] != word[i]:
                if main_chars.count(guess[i])+other_chars.count(guess[i]) < word.count(guess[i]):
                    other_chars.append(guess[i])
    print("Other characters present:", other_chars)

    if count >= 6:
        print("uh oh! You have exhausted all your choices")
        print("The word was", word)
        break

    if guess == word:
        print("Congratulation! You guessed the word correctly:", guess)
